# Generated by Django 3.0.13 on 2022-05-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220329_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='band_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='case_diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='coating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_clocks',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water_resistance',
        ),
        migrations.AddField(
            model_name='product',
            name='cars',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cars'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, max_length=255, verbose_name='Graduation year'),
        ),
    ]
