# Generated by Django 3.0.13 on 2022-05-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220507_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of parts'),
        ),
    ]
