# Generated by Django 3.0.13 on 2022-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Number of parts'),
        ),
    ]
