# Generated by Django 3.0.13 on 2022-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(choices=[('POST-OFFICE', 'Post ofice'), ('SELF-PICKUP', 'Self-pickup')], default=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('NOVA-POSHTA', 'Nova-poshta'), ('UKR-POSHTA', 'Ukr-poshta'), ('Delivery-POSHTA', 'Delivery-poshta')], default='SELF-PICKUP', max_length=22),
        ),
    ]
