# Generated by Django 3.0.13 on 2022-05-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numbers',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of parts'),
        ),
    ]
